#!/bin/bash

# Get username of the currently logged in user
username=$(who | cut -d' ' -f1 | sort | uniq)

case "$2" in
        up)
			su -c "todo.sh google push" $username
        ;;
        down)
        ;;
esac