#!/bin/bash

# Get username of the currently logged in user
username=$(who | cut -d' ' -f1 | sort | uniq)

case "$2" in
        up)
			su -c "todo.sh -d /home/orschiro/Dropbox/Todo/todo.cfg -t google pull" $username
			su -c "todo.sh -d /home/orschiro/Dropbox/Todo/todo.cfg -t google push" $username
        ;;
        down)
        ;;
esac