#!/bin/sh

INTERFACE=$1 # The interface which is brought up or down
STATUS=$2 # The new state of the interface

case "$STATUS" in
    up) # $INTERFACE is up
        USERS=$(ps -o user --no-headers -C dropbox)
        killall dropbox
        #for user in $USERS; do
        #    su - $user -c "DISPLAY=$(who | sed -n '/^$user.*(\(:[0-9]*\))$/!d;s//\1/p;q') dropboxd &"
        #done
        su -c "DISPLAY=:0 dropboxd &" orschiro
        ;;
    down) # $INTERFACE is down
        ;;
esac
