#!/bin/sh

case $1 in
    resume|thaw)
	if  [$(cat /sys/class/power_supply/AC/online) = 1]; then
	  /usr/local/bin/powersaving AC
	else
	  /usr/local/bin/powersaving battery
	fi
        ;;
    *)
	echo "Not running 90-AC-battery properly"
	;;
esac
