#!/bin/bash

# Determining if on AC or battery
if cat /sys/class/power_supply/AC/online | grep 0 > /dev/null 2>&1
then
    echo "Laptop is on battery"
    systemctl stop crashplan.service
    systemctl stop insync@orschiro.service
    systemctl stop dropbox@orschiro.service
    /usr/bin/ntpd -gq || true
else
    echo "Laptop is on AC"
    systemctl restart crashplan.service
    systemctl restart insync@orschiro.service
    systemctl restart dropbox@orschiro.service
    /usr/bin/ntpd -gq || true
fi

